# Generated by Django 3.0.5 on 2020-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, unique=True, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=128, unique=True, verbose_name='MAC地址')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('status', models.CharField(choices=[('0', '宕机'), ('1', '正常'), ('2', '高延迟'), ('3', '不可达')], default='宕机', max_length=32, verbose_name='状态')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IP列表',
                'verbose_name_plural': 'IP列表',
            },
        ),
    ]
