# Generated by Django 3.0.5 on 2020-04-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='名称'),
        ),
    ]
