# Generated by Django 3.0.5 on 2020-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0004_auto_20200423_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='comment',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
    ]
