# Generated by Django 3.0.5 on 2020-04-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0005_auto_20200423_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='ip',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='ips',
            name='mac',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='ips',
            name='name',
            field=models.CharField(editable=False, max_length=128, null=True, verbose_name='名称'),
        ),
    ]
