# Generated by Django 3.0.5 on 2020-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0002_auto_20200423_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ips',
            options={'verbose_name': 'IP记录', 'verbose_name_plural': 'IP列表'},
        ),
        migrations.AlterField(
            model_name='ips',
            name='comment',
            field=models.CharField(max_length=128, verbose_name='备注'),
        ),
    ]
