# Generated by Django 3.0.5 on 2020-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0007_auto_20200423_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ips',
            options={'ordering': ['id'], 'verbose_name': 'IP记录', 'verbose_name_plural': 'IP列表'},
        ),
        migrations.AlterField(
            model_name='ips',
            name='status',
            field=models.CharField(choices=[('0', '宕机'), ('1', '正常'), ('2', '高延迟'), ('3', '不稳定')], default='宕机', max_length=32, verbose_name='状态'),
        ),
    ]
