# Generated by Django 3.0.5 on 2020-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_test', '0008_auto_20200501_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(editable=False, max_length=128, unique=True, verbose_name='IP地址')),
                ('comment', models.CharField(blank=True, max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '备注',
                'verbose_name_plural': '备注列表',
                'ordering': ['id'],
            },
        ),
    ]
